data = read.table("data.txt")
col_2 = as.integer(data[,2] / 1000)
col_3 = as.integer(data[,3] / 1000)
print(range(col_2))
print(as.integer(mean(col_2)))
print(as.integer(var(col_2)))
print(as.integer(sd(col_2)))
print(min(col_2))
print(max(col_2))
categories = seq(min(col_3)-1,max(col_3)+8, by = 8)
col_3.cut = cut(col_3, breaks = categories, right = FALSE)
high.freq = table(col_3.cut)
cbind(high.freq)

hist(col_3, breaks =categories, col = "lightgray", xlab = "High", ylab = "Count", main = "Frequency", right = FALSE,bmp(file="aa.bmp"))
dev.off()

plot(head(cbind(data[,4],data[,5]),100),xlab="High",ylab="Low",main="Scatter",bmp(file="bb.bmp"))
dev.off()
